name: "Custom Deploy Action"
description: "W켹asna akcja kompozytowa do wdro콮enia aplikacji"
author: "Zesp칩켹 DevOps"

inputs:
  environment:
    description: '콐rodowisko docelowe (np. staging/prod)'
    required: true
    default: 'staging'
  version:
    description: 'Wersja aplikacji do wdro콮enia (np. 1.2.3)'
    required: true
  notify-team:
    description: 'Czy powiadomi캖 zesp칩켹 (true/false)'
    required: false
    default: 'false'
  github-token:
    description: 'Token GitHub do operacji przez API'
    required: true

outputs:
  deployment-url:
    description: 'URL, pod kt칩rym jest dost캧pna aplikacja'
  deployment-time:
    description: 'Czas zako켻czenia wdro콮enia (UTC, ISO8601)'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Ustaw zmienne wej콑ciowe
      shell: bash
      run: |
        echo "콐rodowisko: ${{ inputs.environment }}"
        echo "Wersja: ${{ inputs.version }}"
        echo "Notify-team: ${{ inputs['notify-team'] }}"

    - name: Wykonaj skrypt wdro콮enia
      id: deploy
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/deploy.sh"
        output="$("${{ github.action_path }}/deploy.sh" \
          "${{ inputs.environment }}" \
          "${{ inputs.version }}" \
          "${{ inputs['notify-team'] }}")"
        # Za켹칩콮my, 콮e deploy.sh wypisuje JSON: {"url":"...","time":"..."}
        echo "$output" > result.json
        echo "::set-output name=deployment-url::$(jq -r .url < result.json)"
        echo "::set-output name=deployment-time::$(jq -r .time < result.json)"

    - name: Powiadom GitHub o statusie wdro콮enia
      if: ${{ inputs['notify-team'] == 'true' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const url  = "${{ steps.deploy.outputs.deployment-url }}";
          const time = "${{ steps.deploy.outputs.deployment-time }}";
          github.issues.createComment({
            issue_number: context.issue.number || 0,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `游 Aplikacja wdro콮ona w 콑rodowisku **${{ inputs.environment }}**!\n> URL: ${url}\n> Czas: ${time}`
          });
